language: python

dist: xenial

python:
  - 3.6
  - 3.7
  
env:
  - DJANGO=Django<2
  - DJANGO=Django<3
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:

     
after_success: coveralls

