language: python

python:
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=Django<2
  - DJANGO=Django<3
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:
   - python: 3.4
     env: DJANGO=https://github.com/django/django/tarball/master
   - python: 3.4
     env: DJANGO<2
   - python: 3.4
     env: DJANGO<3

   - python: 3.5
     env: DJANGO<3
   - python: 3.5
     env: DJANGO=https://github.com/django/django/tarball/master

     
after_success: coveralls

