language: python

python:
  - 3.4
  - 3.6

env:
  - DJANGO=Django<2
  - DJANGO=Django<3
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

after_success: coveralls
