language: python

python:
  - 2.7
  - 3.3
  - 3.6

env:
  - DJANGO=Django==1.11
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:
   - python: 2.7
     env: DJANGO=https://github.com/django/django/tarball/master

after_success: coveralls
